add ability to delete query directly
Yuyz0112/smart-cache pull request #4
Opened 2019-09-05 06:10 UTC by YEriin

2019-09-05 06:33 UTC, Yuyz0112 commented
`client.deleteCache(undefined, undefined, 'pureText')`

这个 API 不好。。我们重构一下 deleteCache 的 API 吧，分为两个参数
1. 第一个参数是 cache selector，可以有 `{ typename }`, `{ typename, idobj }`, `{ query }` 三种形式。
2. 第二个参数是 options，目前可以有是否 refetch `{ refetch }`

2019-09-06 05:56 UTC, Yuyz0112 requested changes

2019-09-06 05:56 UTC, Yuyz0112 commented on src/index.ts
> +    if (options && !options.refetch) {
options 需要一个默认值，refetch default 为 true

2019-09-06 07:09 UTC, YEriin commented on src/index.ts
> +    if (options && !options.refetch) {
现在不传的逻辑下，就是 refetch

2019-09-06 08:30 UTC, merged